<?php

namespace ItechSup\QuestionnaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    public function findAllByCategorie($idCateg)
    {
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT q FROM ItechSupQuestionnaireBundle:Question q
            WHERE q.categorie = :idCateg'
                )->setParameter('idCateg', $idCateg);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
