<?php

namespace ItechSup\QuestionnaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends EntityRepository
{

    /**
     * Select questionnaires which are not complete by this user
     * 
     * @param int $user
     * @return string
     */
    public function findAllIsNotComplete($user)
    {
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT quest FROM ItechSupQuestionnaireBundle:Questionnaire quest
            WHERE quest.id NOT IN(
            SELECT DISTINCT q.id FROM ItechSupQuestionnaireBundle:Reponse r
            JOIN r.question qt
            JOIN qt.categorie c
            JOIN c.questionnaire q
            WHERE r.user = :idUser)'
                )->setParameter('idUser', $user);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
